use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// API Key CRUD — presentation/handlers/team/api_key_handler.go
// (`/api/v1/team/api-keys`; POST/GET are auth-only, DELETE targets `:id`)
//
// `Create` は組織スコープ固定（handler が `CreateApiKeyParams` を
// `OrganizationID: common.ResolveOrganizationID(c)` のみで組み立てており、
// リクエストに scope フィールドは存在しない）。`List`/`Revoke` はユーザー単位
// （`useCase.List(ctx, user.ID)` / `useCase.Revoke(ctx, user.ID, keyID)`）で
// 組織ヘッダーを見ないが、本CLIでは他コマンドと同様に `--org` を受け付ける。
//
// レスポンスはここだけ他エンドポイント（大半がcamelCase）と異なり、
// `application/resources/api_key_resource.go` の json タグがそのまま
// snake_case（`key_prefix`/`last_used_at`/`revoked_at`）— そのためこの
// ファイルには `rename_all` を付けていない（Rustのフィールド名がそのまま
// wire formatと一致する）。
//
// 自動生成キー（`IsAutoGenerated`、MCP/CLI/Codexがローテートしながら発行）は
// `List` のレスポンスに含まれない（`ApiKeyUseCase.List` 内でユーザー向け表示
// から除外済み。誤って手動失効されないようにするため）。
// ---------------------------------------------------------------------------

/// `POST /api/v1/team/api-keys` (`createApiKeyRequest`)。`name` は任意 —
/// 空ならバックエンドが `"API Key (YYYY-MM-DD)"` 形式のデフォルト名を生成する。
#[derive(Debug, Clone, Serialize, Default)]
pub struct ApiKeyCreateRequest {
    #[serde(skip_serializing_if = "str::is_empty")]
    pub name: String,
}

/// `ApiKeyResource`（`GET /api/v1/team/api-keys` の各要素 / `Revoke` は
/// レスポンスに含めない）。生キーは含まれない。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiKey {
    pub id: String,
    pub key_prefix: String,
    pub name: String,
    #[serde(default)]
    pub last_used_at: Option<String>,
    pub created_at: String,
    #[serde(default)]
    pub revoked_at: Option<String>,
}

/// `ApiKeyCreatedResource`（`POST /api/v1/team/api-keys` の 201 レスポンス）。
/// `key` に平文シークレットが入るのはこの応答のみ — 二度と取得できないため、
/// 呼び出し側はこの場でユーザーに保存を促すこと。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiKeyCreated {
    pub id: String,
    pub key: String,
    pub key_prefix: String,
    pub name: String,
    pub created_at: String,
}

/// `DELETE /api/v1/team/api-keys/:id` のレスポンス本体（`gin.H{"message": ...}`）。
/// 204ではなくJSONボディが返るため、`ApiClient::delete_json` で受ける。
#[derive(Debug, Clone, Deserialize, Default)]
pub struct ApiKeyRevokeResponse {
    #[serde(default)]
    pub message: String,
}
